<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Migrations\**" />
    <EmbeddedResource Remove="Persistence\Migrations\**" />
    <None Remove="Persistence\Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICV.Application\ICV.Application.csproj" />
    <ProjectReference Include="..\ICV.Domain\ICV.Domain.csproj" />
    <ProjectReference Include="..\ICV.Shared\ICV.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Services\Export\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.18.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />

		<PackageReference Include="PdfPig" Version="0.1.16-alpha-202608201713-f131e" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
	</ItemGroup>
	
</Project>
